name: CI Backend

on:
  push:
    branches: [main, develop]
    paths:
      - 'getrady-backend/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'getrady-backend/**'
      - '.github/workflows/ci-backend.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: getrady-backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: getrady-backend/package-lock.json

      - name: Install
        run: npm ci --no-audit --prefer-offline

      - name: Lint
        run: npm run lint --if-present

      - name: Test (CI)
        run: npm test -- --ci --passWithNoTests

      - name: Build
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: getrady-backend/dist
          if-no-files-found: error