name: CI Backend

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'getrady-backend/**'
      - '.github/workflows/ci-backend.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: backend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: getrady-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: getrady-backend/package-lock.json

      - name: Install deps
        run: npm ci --no-audit --prefer-offline

      - name: Run tests (CI)
        run: npm test -- --ci --runInBand
        env:
          CI: 'true'