name: CI Frontend

on:
  push:
    branches: [main, develop]
    paths:
      - 'getrady-frontend/**'
      - '.github/workflows/ci-frontend.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'getrady-frontend/**'
      - '.github/workflows/ci-frontend.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: getrady-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: getrady-frontend/package-lock.json

      - name: Install deps
        run: npm ci --no-audit --prefer-offline

      - name: Lint
        run: npm run lint --if-present

      - name: Run tests (CI)
        run: npm run test:ci
        env:
          CI: 'true'