name: CI Frontend

on:
  push:
    branches: [main, develop]
    paths:
      - 'getrady-frontend/**'
      - '.github/workflows/ci-frontend.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'getrady-frontend/**'
      - '.github/workflows/ci-frontend.yml'

jobs:
  test:
    name: frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: getrady-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: getrady-frontend/package-lock.json
      - run: npm ci
      - run: npm run test -- --ci