name: CI Frontend

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'getrady-frontend/**'
      - '.github/workflows/ci-frontend.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: getrady-frontend
    steps:
      - name: Checkout (PR head SHA, full fetch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: false
          persist-credentials: false

      - name: Mark repo as safe (avoid git 128)
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: getrady-frontend/package-lock.json

      - name: Install deps
        run: npm ci --no-audit --prefer-offline

      - name: Run tests (CI)
        run: npm run test:ci
        env:
          CI: 'true'